In [1]:
# two dimensional array = matrix
# numpy arrays need the same data type

#numpy data types
#bool
#int (16,32,64)
#float (16, 32, 64)
#string (string or unicode)

#.dtype      returns datatype
#na          not available
#nan         not a number    

In [2]:
#numpy.array() is constructor which can take list/list of lists to create vector/matrix

import numpy

a_vector = numpy.array(['a', 'b', 'c'])
print(a_vector[1])

a_matrix = numpy.array([['a', 'b'], ['c', 'd']])
print(a_matrix[1,0])

print(a_matrix.shape)

b
c
(2, 2)


In [3]:
# read a file into numpy
# specify parameters for delimiter, datatype, skip header

world_alcohol = numpy.genfromtxt("world_alcohol.csv", delimiter=",", dtype='U75', skip_header=1)

print(world_alcohol)
print()

print(world_alcohol[0:2])     # slice first 2 rows
print()

print(world_alcohol[:,1])     # slice all rows, second column
print()

print(world_alcohol[:,0:2])   # all rows, first 2 colums
print()

print(world_alcohol[:,[1,4]]) # all rows, first and 5th column
print()

print(world_alcohol[:,0::3]) # all rows, first and 5th column, alternative specifying stride

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ..., 
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']]

['Western Pacific' 'Americas' 'Africa' ..., 'Europe' 'Western Pacific'
 'Africa']

[['1986' 'Western Pacific']
 ['1986' 'Americas']
 ['1985' 'Africa']
 ..., 
 ['1986' 'Europe']
 ['1987' 'Western Pacific']
 ['1986' 'Africa']]

[['Western Pacific' '0']
 ['Americas' '0.5']
 ['Africa' '1.62']
 ..., 
 ['Europe' '2.54']
 ['Western Pacific' '0']
 ['Africa' '5.15']]

[['1986' 'Wine']
 ['1986' 'Other']
 ['1985' 'Wine']
 ..., 
 ['1986' 'Spirits']
 ['1987' 'Other']
 ['1986' 'Other']]


In [4]:
# finding values

country_is_algeria = world_alcohol[:,2] == 'Algeria' # return array with all boolean values
print(country_is_algeria)
print()

country_algeria = world_alcohol[country_is_algeria] # can use the result of a comparison to return those values
print(country_algeria)


[False False False ..., False False False]

[['1984' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Beer' '0.17']
 ['1987' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1984' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Beer' '0.16']
 ['1989' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1989' 'Africa' 'Algeria' 'Wine' '0.23']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1984' 'Africa' 'Algeria' 'Wine' '0.12']
 ['1985' 'Africa' 'Algeria' 'Beer' '0.19']
 ['1985' 'Africa' 'Algeria' 'Other' '0']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1985' 'Africa' 'Algeria' 'Wine' '0.11']
 ['1986' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Other' '0']
 ['1987' 'Africa' 'Algeria' 'Other' '0']
 ['1984' 'Africa' 'Algeria' 'Beer' '0.2']
 ['1985' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Wine' '0.1']]


In [5]:
# working with vectors

v = numpy.array(range(1,11))

equal_to_ten_and_five = (v == 10) & (v == 5) # multiple comparisons
print(equal_to_ten_and_five)

equal_to_ten_or_five = (v == 10) | (v == 5)
print(equal_to_ten_or_five)

v[equal_to_ten_or_five] = 50     #  can also use to replace
print(v)

v_float = v.astype(float)   # change array type
print(v_float)


[False False False False False False False False False False]
[False False False False  True False False False False  True]
[ 1  2  3  4 50  6  7  8  9 50]
[  1.   2.   3.   4.  50.   6.   7.   8.   9.  50.]


In [6]:
# common computations

v = numpy.array(range(1,11))

print(numpy.sum(v))
print(numpy.mean(v))
print(numpy.min(v))
print(numpy.max(v))

vals = numpy.array([[1,2,3], [10,20,30], [100, 200, 300]])
print(vals.sum(axis=0)) # perform on each column
print(vals.sum(axis=1)) # perform on each row


55
5.5
1
10
[111 222 333]
[  6  60 600]


In [7]:
# Example: spririts consumed in Poland

is_poland = (world_alcohol[:,2] == 'Poland') & (world_alcohol[:,3] == 'Spirits')
poland = world_alcohol[is_poland]

spirits = poland[poland[:,0].argsort()]
print(spirits)

spirits_average = spirits[:,4].astype(float).mean()
print(spirits_average)

[['1984' 'Europe' 'Poland' 'Spirits' '5.32']
 ['1985' 'Europe' 'Poland' 'Spirits' '5.47']
 ['1986' 'Europe' 'Poland' 'Spirits' '6.02']
 ['1987' 'Europe' 'Poland' 'Spirits' '6.18']
 ['1989' 'Europe' 'Poland' 'Spirits' '6.08']]
5.814
